package com.mandisoft.services.member.controller;

import com.mandisoft.services.member.entity.BuyEntries;
import com.mandisoft.services.member.entity.GrainType;
import com.mandisoft.services.member.repository.BuyEntriesRepository;
import com.mandisoft.services.member.repository.GrainTypeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/grains") // This means URL's start with /demo (after Application path)
public class GrainTypeController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private GrainTypeRepository grainTypeRepository;

    @GetMapping(path="")
    public @ResponseBody Iterable<GrainType> getAllGrainTypes() {
        return grainTypeRepository.findAll();
    }
}